version: '3'

services:
  postgres-compose:
    image: postgres
    container_name: pg-cep
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: dbcep
    ports:
      - "3306:5432"
